version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_ENDPOINT=${REACT_APP_API_BASE_ENDPOINT}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_ENDPOINT
